version: '3.4'

services:
    app:
        build:
            context: .
            target: test
        ports:
            - 8000
        volumes:
            - ./bireme/:/app/
            - static_volume:/app/static_files
        env_file:
            - ./.env.test
        container_name: accounts
        command: gunicorn --workers 4 --bind 0.0.0.0:8000 accounts.wsgi --reload --timeout 1000 

    nginx:
        image: nginx:1.18-alpine
        ports:
            - 80:80
        volumes:
            - ./etc/nginx:/etc/nginx/conf.d
            - static_volume:/app/static_files
        depends_on:
            - app
        container_name: accounts-nginx
volumes:
    static_volume: