# Generated by Django 5.2.3 on 2025-06-24 14:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CooperativeCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='updated')),
                ('code', models.CharField(max_length=55, unique=True, verbose_name='code')),
                ('institution', models.TextField(blank=True, null=True, verbose_name='institution')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utils.country', verbose_name='country')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cooperative center',
                'verbose_name_plural': 'cooperative centers',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='updated')),
                ('acronym', models.CharField(max_length=255, verbose_name='acronym')),
                ('type', models.CharField(blank=True, choices=[('national', 'National'), ('thematic', 'Thematic'), ('institutional', 'Institutional')], max_length=30, verbose_name='type')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='utils.country', verbose_name='country')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='main.cooperativecenter', verbose_name='Responsible Cooperative Center')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'network',
                'verbose_name_plural': 'networks',
            },
        ),
        migrations.CreateModel(
            name='NetworkMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.cooperativecenter', verbose_name='Cooperative Center')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.network')),
            ],
            options={
                'verbose_name': 'Network Membership',
                'verbose_name_plural': 'Network Memberships',
            },
        ),
        migrations.AddField(
            model_name='network',
            name='members',
            field=models.ManyToManyField(through='main.NetworkMembership', to='main.cooperativecenter'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('type', models.CharField(choices=[('basic', 'Basic'), ('advanced', 'Advanced')], default='basic', max_length=30, verbose_name='type')),
                ('cooperative_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.cooperativecenter', verbose_name='Cooperative Center')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='updated')),
                ('acronym', models.CharField(max_length=55, verbose_name='acronym')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
            },
        ),
        migrations.CreateModel(
            name='RoleLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt-br', 'Brazilian Portuguese'), ('es', 'Spanish')], max_length=10, verbose_name='language')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.role', verbose_name='role')),
            ],
            options={
                'verbose_name': 'role translation',
                'verbose_name_plural': 'role translations',
            },
        ),
        migrations.CreateModel(
            name='RoleService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.role')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='updated')),
                ('acronym', models.CharField(max_length=55, verbose_name='acronym')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('roles', models.ManyToManyField(through='main.RoleService', to='main.role')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
            },
        ),
        migrations.AddField(
            model_name='roleservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.service'),
        ),
        migrations.CreateModel(
            name='ServiceLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt-br', 'Brazilian Portuguese'), ('es', 'Spanish')], max_length=10, verbose_name='language')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'service translation',
                'verbose_name_plural': 'service translations',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='updated')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'topic',
                'verbose_name_plural': 'topics',
            },
        ),
        migrations.AddField(
            model_name='network',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.topic', verbose_name='topic'),
        ),
        migrations.CreateModel(
            name='TopicLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt-br', 'Brazilian Portuguese'), ('es', 'Spanish')], max_length=10, verbose_name='language')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.topic', verbose_name='topic')),
            ],
            options={
                'verbose_name': 'topic translation',
                'verbose_name_plural': 'topic translations',
            },
        ),
        migrations.CreateModel(
            name='UserRoleService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.roleservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
